<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="2" failed="1" total="3" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Suite" duration-ms="4740" started-at="2017-07-18T04:03:55Z" finished-at="2017-07-18T04:04:00Z">
    <groups>
    </groups>
    <test name="Test1" duration-ms="4718" started-at="2017-07-18T04:03:55Z" finished-at="2017-07-18T04:04:00Z">
      <class name="DD_TestCases.LoginTest">
        <test-method status="PASS" signature="isSkip()[pri:0, instance:DD_TestCases.LoginTest@57bc27f5]" name="isSkip" is-config="true" duration-ms="15" started-at="2017-07-18T09:33:55Z" finished-at="2017-07-18T09:33:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- isSkip -->
        <test-method status="SKIP" signature="doLogin(java.lang.String, java.lang.String)[pri:0, instance:DD_TestCases.LoginTest@57bc27f5]" name="doLogin" duration-ms="2281" started-at="2017-07-18T09:33:55Z" data-provider="getData" finished-at="2017-07-18T09:33:57Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[tutorial]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[tutorial]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:92)
	at org.junit.Assert.fail(Assert.java:100)
	at DD_TestCases.LoginTest.doLogin(LoginTest.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:816)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1124)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLogin -->
        <test-method status="PASS" signature="afterTest(org.testng.ITestResult)[pri:0, instance:DD_TestCases.LoginTest@57bc27f5]" name="afterTest" is-config="true" duration-ms="3" started-at="2017-07-18T09:33:58Z" finished-at="2017-07-18T09:33:58Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=doLogin status=SKIP method=LoginTest.doLogin(java.lang.String, java.lang.String)[pri:0, instance:DD_TestCases.LoginTest@57bc27f5] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method status="SKIP" signature="doLogin(java.lang.String, java.lang.String)[pri:0, instance:DD_TestCases.LoginTest@57bc27f5]" name="doLogin" duration-ms="879" started-at="2017-07-18T09:33:58Z" data-provider="getData" finished-at="2017-07-18T09:33:58Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[tutorial]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[tutorial]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:92)
	at org.junit.Assert.fail(Assert.java:100)
	at DD_TestCases.LoginTest.doLogin(LoginTest.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:963)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1142)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLogin -->
        <test-method status="PASS" signature="afterTest(org.testng.ITestResult)[pri:0, instance:DD_TestCases.LoginTest@57bc27f5]" name="afterTest" is-config="true" duration-ms="1" started-at="2017-07-18T09:33:59Z" finished-at="2017-07-18T09:33:59Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=doLogin status=SKIP method=LoginTest.doLogin(java.lang.String, java.lang.String)[pri:0, instance:DD_TestCases.LoginTest@57bc27f5] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
        <test-method status="FAIL" signature="doLogin(java.lang.String, java.lang.String)[pri:0, instance:DD_TestCases.LoginTest@57bc27f5]" name="doLogin" duration-ms="846" started-at="2017-07-18T09:33:59Z" data-provider="getData" finished-at="2017-07-18T09:34:00Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[tutorial]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[tutorial]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError
	at org.junit.Assert.fail(Assert.java:92)
	at org.junit.Assert.fail(Assert.java:100)
	at DD_TestCases.LoginTest.doLogin(LoginTest.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.retryFailed(Invoker.java:963)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1142)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:774)
	at org.testng.TestRunner.run(TestRunner.java:624)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:359)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:354)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:312)
	at org.testng.SuiteRunner.run(SuiteRunner.java:261)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1215)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1140)
	at org.testng.TestNG.run(TestNG.java:1048)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:137)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:58)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- doLogin -->
        <test-method status="PASS" signature="afterTest(org.testng.ITestResult)[pri:0, instance:DD_TestCases.LoginTest@57bc27f5]" name="afterTest" is-config="true" duration-ms="133" started-at="2017-07-18T09:34:00Z" finished-at="2017-07-18T09:34:00Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[[TestResult name=doLogin status=FAILURE method=LoginTest.doLogin(java.lang.String, java.lang.String)[pri:0, instance:DD_TestCases.LoginTest@57bc27f5] output={null}]]]>
              </value>
            </param>
          </params>
          <reporter-output>
          </reporter-output>
        </test-method> <!-- afterTest -->
      </class> <!-- DD_TestCases.LoginTest -->
    </test> <!-- Test1 -->
    <test name="Test2" duration-ms="1" started-at="2017-07-18T04:04:00Z" finished-at="2017-07-18T04:04:00Z">
      <class name="DD_TestCases.RegisterTest">
        <test-method status="PASS" signature="init()[pri:0, instance:DD_TestCases.RegisterTest@79207381]" name="init" is-config="true" duration-ms="9320" started-at="2017-07-18T09:33:46Z" finished-at="2017-07-18T09:33:55Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- init -->
        <test-method status="PASS" signature="isSkip()[pri:0, instance:DD_TestCases.RegisterTest@79207381]" name="isSkip" is-config="true" duration-ms="1" started-at="2017-07-18T09:34:00Z" finished-at="2017-07-18T09:34:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- isSkip -->
        <test-method status="PASS" signature="close()[pri:0, instance:DD_TestCases.RegisterTest@79207381]" name="close" is-config="true" duration-ms="416" started-at="2017-07-18T09:34:00Z" finished-at="2017-07-18T09:34:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- close -->
      </class> <!-- DD_TestCases.RegisterTest -->
    </test> <!-- Test2 -->
  </suite> <!-- Suite -->
</testng-results>
